<?php

namespace Inck\NotificationBundle\Entity;

use DateInterval;
use Doctrine\ORM\EntityRepository;
use Inck\NotificationBundle\Model\NotificationRepositoryInterface;

/**
 * SubscriberNotificationRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SubscriberNotificationRepository extends EntityRepository implements NotificationRepositoryInterface
{
    /**
     * @param SubscriberNotification $notification
     * @param \DateInterval $interval
     * @return bool
     */
    public function isAlreadySent($notification, DateInterval $interval)
    {
        $qb = $this->createQueryBuilder('n');
        $limit = new \DateTime();
        $limit->sub($interval);

        $qb
            ->select('COUNT(n)')
            ->where('n.subscriber = :subscriber')
            ->setParameter('subscriber', $notification->getSubscriber())
            ->andWhere('n.to = :to')
            ->setParameter('to', $notification->getTo())
            ->andWhere('n.createdAt >= :createdAt')
            ->setParameter('createdAt', $limit->format('Y-m-d H:i:s'));

        return ((int) $qb->getQuery()->getSingleScalarResult() !== 0);
    }
}
