services:
    inck_subscription.twig.subscription_extension:
        class: Inck\SubscriptionBundle\Twig\SubscriptionExtension
        arguments: [@security.context, @doctrine.orm.entity_manager, %inck_subscription.aliases%]
        tags:
            - { name: twig.extension }
    inck_subscription.rpc.subscription_manager:
        class: Inck\SubscriptionBundle\RPC\SubscriptionManager
        arguments: [@doctrine.orm.entity_manager, %inck_subscription.aliases%]