services:
    subscription.twig_extension:
        class: Inck\SubscriptionBundle\Twig\SubscriptionExtension
        arguments: [@security.authorization_checker, @security.token_storage, @doctrine.orm.entity_manager, %inck_subscription.aliases%]
        tags:
            - { name: twig.extension }
    subscription.handler:
        class: Inck\SubscriptionBundle\RPC\SubscriptionHandler
        arguments: [@ratchet.entity_manager, @event_dispatcher, @logger, %inck_subscription.aliases%]
        tags:
            - { name: inck_ratchet.rpc, alias: subscription }
            - { name: monolog.logger, channel: inck_ratchet }
