services:
    inck_subscription.twig.subscription_extension:
        class: Inck\SubscriptionBundle\Twig\SubscriptionExtension
        arguments: [@security.context, @doctrine.orm.entity_manager, %inck_subscription.aliases%]
        tags:
            - { name: twig.extension }
    inck_subscription.rpc.subscription_handler:
        class: Inck\SubscriptionBundle\RPC\SubscriptionHandler
        arguments: [@doctrine.orm.entity_manager, @event_dispatcher, %inck_subscription.aliases%]
        tags:
            -  { name: inck_ratchet.rpc, alias: subscription }
