<?php

namespace Inck\NotifBundle\Entity;

use Doctrine\ORM\EntityRepository;
use Symfony\Component\Security\Core\User\UserInterface;

/**
 * SubscriptionRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SubscriptionRepository extends EntityRepository
{
    /**
     * @param UserInterface $subscriber
     * @return mixed Subscription|null
     */
    public function getOneBySubscriber($subscriber)
    {
        $query = $this
            ->createQueryBuilder('s')
            ->select('s')
            ->andWhere('s.subscriber = :subscriber')
            ->setParameter('subscriber', $subscriber)
            ->getQuery()
        ;

        return $query->getOneOrNullResult();
    }
}
