imports:
    - { resource: parameters.yml }
    - { resource: security.yml }

framework:
    #esi:             ~
    translator:      ~
    secret:          "%secret%"
    router:
        resource: "%kernel.root_dir%/config/routing.yml"
        strict_requirements: ~
    form:            ~
    csrf_protection: ~
    validation:      { enabled: true, api: 2.4, enable_annotations: true }
    templating:
        engines: ['twig']
        #assets_version: SomeVersionScheme
    default_locale:  "%locale%"
    trusted_hosts:   ~
    trusted_proxies: ~
    session:
        # handler_id set to null will use default session handler from php.ini
        handler_id:  ~
    fragments:       ~
    http_method_override: true

# Twig Configuration
twig:
    debug:            "%kernel.debug%"
    strict_variables: "%kernel.debug%"
    form:
        resources:
            - BraincraftedBootstrapBundle:Form:bootstrap.html.twig

# Assetic Configuration
assetic:
    debug:          "%kernel.debug%"
    use_controller: false
    bundles:        [ InckCoreBundle, InckArticleBundle, InckUserBundle, FOSUserBundle, AvocodeFormExtensionsBundle ]
    #java: /usr/bin/java
    filters:
        less:
            #node: /usr/bin/nodejs
            #node_paths: [/usr/local/lib/node_modules]
            #Paths for Mac Users
            node: /usr/local/bin/node
            node_paths: [/usr/local/bin/node, /usr/local/lib/node_modules]
            apply_to: "\.less$"
        cssrewrite: ~
        #closure:
        #    jar: "%kernel.root_dir%/Resources/java/compiler.jar"
        yui_css:
            jar: "%kernel.root_dir%/Resources/java/yuicompressor.jar"
        yui_js:
            jar: "%kernel.root_dir%/Resources/java/yuicompressor.jar"

# Doctrine Configuration
doctrine:
    dbal:
        driver:   "%database_driver%"
        host:     "%database_host%"
        port:     "%database_port%"
        dbname:   "%database_name%"
        user:     "%database_user%"
        password: "%database_password%"
        charset:  UTF8
        # if using pdo_sqlite as your database driver, add the path in parameters.yml
        # e.g. database_path: "%kernel.root_dir%/data/data.db3"
        # path:     "%database_path%"

    orm:
        auto_generate_proxy_classes: "%kernel.debug%"
        auto_mapping: true

# Swiftmailer Configuration
swiftmailer:
    transport: "%mailer_transport%"
    encryption: "%mailer_encryption%"
    auth_mode:  "%mailer_auth_mode%"
    host: "%mailer_host%"
    username: "%mailer_user%"
    password: "%mailer_password%"
    spool: { type: memory }

# BraincrafterBootstrap Configuration
braincrafted_bootstrap:
    jquery_path: %kernel.root_dir%/../web/components/jquery/jquery.min.js
    less_filter: less

# KNP Configuration
knp_menu:
    twig:
        template: BraincraftedBootstrapBundle:Menu:bootstrap.html.twig
    templating: false
    default_renderer: twig

# FOSUserBundle Configuration
fos_user:
    db_driver: orm
    firewall_name: main
    user_class: Inck\UserBundle\Entity\User
    profile:
          form:
              type: inck_user_profile
    registration:
        form:
            type: inck_user_registration

# OrnicarGravatar Configuration
ornicar_gravatar:
    rating: g
    size: 80
    default: mm

# AvocodeFormExtensionsBundle Configuration
avocode_form_extensions:
    upload_manager:        vich_uploader

# VichUploaderBundle Configuration
vich_uploader:
    db_driver: orm
    gaufrette: false
    storage:   vich_uploader.storage.file_system
    mappings:
        article_image:
            uri_prefix:           /article/image
            upload_destination:   %kernel.root_dir%/../web/article/image
            namer:                vich_uploader.namer_uniqid
            inject_on_load:       true
            delete_on_remove:     true
            delete_on_update:     true
