inck_stat:
    resource: "@InckStatBundle/Controller/"
    type:     annotation
    prefix:   /

inck_bid:
    resource: "@InckBidBundle/Resources/config/routing.yml"
    prefix:   /

inck_core:
    resource: "@InckCoreBundle/Controller/"
    type:     annotation
    prefix:   /

inck_user:
    resource: "@InckUserBundle/Controller/"
    type:     annotation
    prefix:   /

inck_article:
    resource: "@InckArticleBundle/Controller/"
    type:     annotation
    prefix:   /

inck_subscription:
    resource: "@InckSubscriptionBundle/Controller/"
    type:     annotation
    prefix:   /

inck_notification:
    resource: "@InckNotificationBundle/Controller/"
    type:     annotation
    prefix:   /

fos_user_security:
    resource: "@FOSUserBundle/Resources/config/routing/security.xml"

fos_user_profile:
    resource: "@FOSUserBundle/Resources/config/routing/profile.xml"
    prefix: /profile

fos_user_register:
    resource: "@FOSUserBundle/Resources/config/routing/registration.xml"
    prefix: /register

fos_user_resetting:
    resource: "@FOSUserBundle/Resources/config/routing/resetting.xml"
    prefix: /resetting

fos_user_change_password:
    resource: "@FOSUserBundle/Resources/config/routing/change_password.xml"
    prefix: /profile

fos_user_group:
    resource: "@FOSUserBundle/Resources/config/routing/group.xml"
    prefix: /group

fos_js_routing:
    resource: "@FOSJsRoutingBundle/Resources/config/routing/routing.xml"

_imagine:
    resource: .
    type:     imagine

hwi_oauth_redirect:
    resource: "@HWIOAuthBundle/Resources/config/routing/redirect.xml"
    prefix:   /login

hwi_oauth_login:
    resource: "@HWIOAuthBundle/Resources/config/routing/login.xml"
    prefix:   /login

facebook_login:
    pattern: /login/check-facebook

google_login:
    pattern: /login/check-google

facebook_link:
    pattern: /login/facebook

google_link:
    pattern: /login/google

NelmioJsLoggerBundle:
    resource: "@NelmioJsLoggerBundle/Resources/config/routing.xml"
    prefix:   /nelmio-js-logger

PrestaSitemapBundle:
    resource: "@PrestaSitemapBundle/Resources/config/routing.yml"
    prefix:   /
