services:
    inck_notif.twig.subscription_extension:
        class: Inck\NotifBundle\Twig\SubscriptionExtension
        arguments: [@security.context, @doctrine.orm.entity_manager, %inck_notif.aliases%]
        tags:
            - { name: twig.extension }

    inck_notif.server.server_service:
        class: Inck\NotifBundle\Server\ServerService
        arguments: [@session, @doctrine.orm.entity_manager, %inck_notif.aliases%]
