services:
    inck_notification.rpc.notification_handler:
        class: Inck\NotificationBundle\RPC\NotificationHandler
        arguments: [@doctrine.orm.entity_manager, @event_dispatcher]
        tags:
            -  { name: inck_ratchet.rpc, alias: notification }
    inck_notification.listener.notification_listener:
        class: Inck\NotificationBundle\Listener\NotificationListener
        arguments: [@doctrine.orm.entity_manager, @templating, @inck_ratchet.server.client_manager_service]
        tags:
            - { name: kernel.event_listener, event: notification.created,   method: onNotificationCreated   }
            - { name: kernel.event_listener, event: notification.displayed, method: onNotificationDisplayed }
