services:
    notification.handler:
        class: Inck\NotificationBundle\RPC\NotificationHandler
        arguments: [@ratchet.entity_manager]
        tags:
            -  { name: inck_ratchet.rpc, alias: notification }
    notification.listener:
        class: Inck\NotificationBundle\Listener\NotificationListener
        arguments: [@ratchet.entity_manager, @notification.manager]
        tags:
            - { name: kernel.event_listener, event: notification.create, method: onNotificationCreate }
    notification.manager:
        class: Inck\NotificationBundle\Manager\NotificationManager
        arguments: [@ratchet.entity_manager, @templating, @ratchet.client_manager]
