<?php

namespace Inck\UserBundle\Entity;

/**
 * BookshelfRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class BookshelfRepository extends \Doctrine\ORM\EntityRepository
{
}
