<?php

namespace Inck\ArticleBundle\Entity;

use Doctrine\ORM\EntityRepository;
use Inck\UserBundle\Entity\User;

/**
 * ReportRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ReportRepository extends EntityRepository
{
    /**
     * @param $article Article
     * @return int
     */
    public function countByArticle(Article $article)
    {
        $query = $this
            ->createQueryBuilder('r')
            ->select('COUNT(r)')
            ->where('r.article = :article')
            ->setParameter('article', $article)
            ->getQuery()
        ;

        return (int) $query->getSingleScalarResult();
    }

    /**
     * @param Article $article
     * @param User $user
     * @return null|Report
     */
    public function getByArticleAndUser(Article $article, User $user)
    {
        $query = $this
            ->createQueryBuilder('r')
            ->select('r')
            ->where('r.article = :article')
            ->setParameter('article', $article)
            ->andWhere('r.user = :user')
            ->setParameter('user', $user)
            ->getQuery()
        ;

        return $query->getOneOrNullResult();
    }
}
