services:
    inck_ratchet.server.client_manager_service:
        class: Inck\RatchetBundle\Server\ClientManager
        arguments: [@doctrine.orm.entity_manager, @logger]
        tags:
            - { name: monolog.logger, channel: inck_ratchet }
    inck_ratchet.server.server_service:
        class: Inck\RatchetBundle\Server\Server
        arguments: [@inck_ratchet.server.client_manager_service, @logger]
        tags:
            - { name: monolog.logger, channel: inck_ratchet }