services:
    ratchet.client_manager:
        class: Inck\RatchetBundle\Server\ClientManager
    ratchet.entity_manager:
        class: Inck\RatchetBundle\Doctrine\ORM\EntityManager
        public: false
        arguments: [@doctrine.orm.entity_manager]
    ratchet.server:
        class: Inck\RatchetBundle\Server\Server
        arguments: [@ratchet.client_manager, @logger, @ratchet.entity_manager, @notification.manager, @event_dispatcher]
        tags:
            - { name: monolog.logger, channel: inck_ratchet }
    ratchet.message_sender:
        class: Inck\RatchetBundle\Sender\MessageSender
        arguments: [%inck_ratchet.server_address%, %inck_ratchet.zmq_port%]
        tags:
            - { name: monolog.logger, channel: inck_ratchet }
