services:
    inck_ratchet.server.client_manager_service:
        class: Inck\RatchetBundle\Server\ClientManager
        arguments: [@logger]
        tags:
            - { name: monolog.logger, channel: inck_ratchet }
    inck_ratchet.server.server_service:
        class: Inck\RatchetBundle\Server\Server
        arguments: [@inck_ratchet.server.client_manager_service, @logger, @doctrine, @inck_notification.manager.notification_manager]
        tags:
            - { name: monolog.logger, channel: inck_ratchet }
