services:
    inck_ratchet.server.client_manager:
        class: Inck\RatchetBundle\Server\ClientManager
        arguments: [@logger]
        tags:
            - { name: monolog.logger, channel: inck_ratchet }
    inck_ratchet.server.entity_manager:
        class: Inck\RatchetBundle\Doctrine\ORM\EntityManager
        public: false
        arguments: [@doctrine.orm.entity_manager]
    inck_ratchet.server.server:
        class: Inck\RatchetBundle\Server\Server
        arguments: [@inck_ratchet.server.client_manager, @logger, @inck_ratchet.server.entity_manager, @inck_notification.manager.notification_manager]
        tags:
            - { name: monolog.logger, channel: inck_ratchet }
