<?php

namespace Inck\SubscriptionBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * Subscription
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class UserSubscriptionRepository extends EntityRepository
{
    /**
     * countByUser
     *
     * Compte les followers d'un auteur
     * @param $user
     * @return int
     */
    public function countByUser($user)
    {
        $qb = $this
            ->createQueryBuilder('s')
            ->select('COUNT(s)')
            ->where('s.to = :user')
            ->setParameter('user', $user);

        return (int) $qb->getQuery()->getSingleScalarResult();
    }
}
