<?php

namespace Inck\BidBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * BidRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class BidRepository extends EntityRepository
{
}
