parameters:
   inck_user_provider.class: Inck\UserBundle\Security\Core\User\FOSUBUserProvider

services:
    inck_user.profile.form.type:
        class: Inck\UserBundle\Form\Type\ProfileFormType
        arguments: [%fos_user.model.user.class%]
        tags:
            - { name: form.type, alias: inck_user_profile }
    inck_user.registration.form.type:
        class: Inck\UserBundle\Form\Type\RegistrationFormType
        arguments: [%fos_user.model.user.class%]
        tags:
            - { name: form.type, alias: inck_user_registration }
    inck_user.group.form.type:
        class: Inck\UserBundle\Form\Type\GroupFormType
        arguments: [%fos_user.model.user.class%]
        tags:
            - { name: form.type, alias: inck_user_group }
    inck_user.type.users_selector:
        class: Inck\UserBundle\Form\Type\UsersSelectorType
        arguments: ["@doctrine.orm.entity_manager"]
        tags:
            - { name: form.type, alias: inck_userbundle_users_selector }
    inck_user.event_listener.login:
        class: Inck\UserBundle\EventListener\LoginListener
        arguments: [@session, @security.context]
        tags:
            - { name: kernel.event_subscriber }
    inck_user_provider:
          class: "%inck_user_provider.class%"
          #this is the place where the properties are passed to the UserProvider - see config.yml
          arguments: [@fos_user.user_manager,{facebook: facebook_id, google: google_id, twitter: twitter_id}]
