services:
    inck_user.profile.form.type:
        class: Inck\UserBundle\Form\Type\ProfileFormType
        arguments: [%fos_user.model.user.class%]
        tags:
            - { name: form.type, alias: inck_user_profile }
    inck_user.registration.form.type:
        class: Inck\UserBundle\Form\Type\RegistrationFormType
        arguments: [%fos_user.model.user.class%]
        tags:
            - { name: form.type, alias: inck_user_registration }
    inck_user.type.users_selector:
        class: Inck\UserBundle\Form\Type\UsersSelectorType
        arguments: ["@doctrine.orm.entity_manager"]
        tags:
            - { name: form.type, alias: inck_userbundle_users_selector }
    inck_user.event_listener.password_resetting:
        class: Inck\UserBundle\EventListener\LoginListener
        arguments: [@session, @security.context]
        tags:
            - { name: kernel.event_subscriber }